apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 5433
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    app: database
