apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: default
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: api
          image: maykelldocker/postgresql-database:latest
          env:
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: NODE_ENV
              value: development
            - name: POSTGRES_USER
              value: the_user
            - name: POSTGRES_PASSWORD
              value: the_user_password
